name: Build Manager

on:
  workflow_dispatch:

jobs:
  build-manager:
    runs-on: ubuntu-latest
    # environment: signing
    steps:
      - name: Setup need_upload
        id: need_upload
        run: |
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Clone Skroot
        run :
          git clone https://github.com/abcz316/SKRoot-linuxKernelRoot

      - name: Build with Gradle
        run: |
          cd SKRoot-linuxKernelRoot/PermissionManager/
          chmod 777 ./gradlew
          ./gradlew

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: manager
          path: manager/app/build/outputs/apk/release/*.apk
